#
# MongoDB + PHP 7.4 Dockerfile
#
# https://github.com/phpcl/phpcl_jumpstart_mongodb/dockerfile
# v20191219: digest: sha256:e12db96a7b13abd127eb26080f42fbab9924af021d615cd6d45f8b963b5ddde5 size: 3246
#

# Pull base image.
FROM unlikelysource/mongodb_php:latest
COPY ./init.sh /tmp/init.sh
RUN chmod +x /tmp/init.sh
